### ISSUE TITLE
Inject logger in WPF

### ISSUE THREAD

**Issue by utech626** [thomasclaudiushuber/mvvmgen#22]
When I try to inject a logger into a ViewModel an exception is being thrown

	[Inject(typeof(Logger<MainViewModel>), PropertyAccessModifier=AccessModifier.Private, PropertyName = "logger")]
	[Inject(typeof(IEventAggregator))]
	[ViewModel]
	public partial class MainViewModel
	{
		[Property] bool _isBusy;
		[Property] String _busyMessage;	

Generated Code
       public MainViewModel(MvvmGen.Events.IEventAggregator eventAggregator, Microsoft.Extensions.Logging.Logger<FamilyGenerations.ViewModels.MainViewModel> logger)
        {
            this.EventAggregator = eventAggregator;
            this.logger = logger;
            this.OnInitialize();
        }

Exception:
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.Logger`1[FamilyGenerations.ViewModels.MainViewModel]' while attempting to activate 'FamilyGenerations.ViewModels.MainViewModel'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at FamilyGenerations.App.OnStartup(StartupEventArgs e) in C:\TFSSource\Client Applicaitons\FamilyGenerations\FamilyGenerations\App.xaml.cs:line 58
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

This works correctly:
	public partial class MainWindow : Window
	{
		private readonly ILogger<MainWindow> log;
		private readonly MainViewModel _model;

		public MainWindow(MainViewModel model, ILogger<MainWindow> log) //, MainViewModel model
		{
			InitializeComponent();
			this.log = log;
			this._model = model;
			this.DataContext = _model;
			log.LogInformation("Main Window loaded, Staring Application.");
		}
	}

Thanks
Bob

**Comment by thomasclaudiushuber** [comment]
Hi @utech626 ,

thanks for the issue.

I wonder if you also tried the `ILogger<>` interface instead of the `Logger<>` class name:
```
[Inject(typeof(**ILogger**<MainViewModel>), PropertyAccessModifier=AccessModifier.Private, PropertyName = "logger")]
```

Looks like on the `MainWindow` constructor, you're using `ILogger<>`, and on the ViewModel you're using `Logger<>` instead of `ILogger<>`.
